// ReportingType.js
const ADD_REPORT = "ADD_REPORT";
const UPDATE_REPORT = "UPDATE_REPORT";
const DELETE_REPORT = "DELETE_REPORT";
const REPORTS = "REPORTS";
const ADD_REPORT_ERROR = "ADD_REPORT_ERROR";
const REPORT_DETAILS = "REPORT_DETAILS";

export {
  ADD_REPORT,
  UPDATE_REPORT,
  DELETE_REPORT,
  REPORTS,
  ADD_REPORT_ERROR,
  REPORT_DETAILS,
};
