export const PROMISE_SALES = "PROMISE_SALES";
export const ADD_SALE_PROMISE = "ADD_SALE_PROMISE_";
export const ADD_PROMISE_SALE_ERROR = "ADD_PROMISE_SALE_ERROR";
export const PROMISE_SALE_DETAILS = "PROMISE_SALE_DETAILS";
export const DELETE_PROMISE_SALE = "DELETE_PROMISE_SALE";
